#ifndef PCB_H
#define PCB_H

#define	HW_HSE_ENABLED 1 // HSE crystal 8MHz assembled 

// two LEDs on one pin
#define HW_LED_RG1_BIT   (9)
#define HW_LED_RG1_PORT  GPIOA
#define HW_LED_RG1_INIT  GPIO_PIN_INIT(HW_LED_RG1_PORT, HW_LED_RG1_BIT, GPIO_MODE_OUTPUT)
#define HW_LED_RG1_R_ON  {GPIO_BIT_SET(HW_LED_RG1_PORT, HW_LED_RG1_BIT); GPIO_MODE(HW_LED_RG1_PORT, HW_LED_RG1_BIT, GPIO_MODE_OUTPUT);}
#define HW_LED_RG1_G_ON  {GPIO_BIT_CLR(HW_LED_RG1_PORT, HW_LED_RG1_BIT); GPIO_MODE(HW_LED_RG1_PORT, HW_LED_RG1_BIT, GPIO_MODE_OUTPUT);}
#define HW_LED_RG1_OFF   GPIO_MODE(HW_LED_RG1_PORT, HW_LED_RG1_BIT, GPIO_MODE_FLOATING) 

#define HW_LED1_INIT HW_LED_RG1_INIT
#define HW_LED1_ON   HW_LED_RG1_R_ON
#define HW_LED1_OFF  HW_LED_RG1_OFF

#define HW_LED2_ON   HW_LED_RG1_G_ON
#define HW_LED2_OFF  // HW_LED_RG1_OFF


// uart2 == ui
#define HW_UART2_ON 0
#define	HW_UART2_RX_BIT  3
#define	HW_UART2_RX_PORT GPIOA
#define	HW_UART2_TX_BIT  2
#define	HW_UART2_TX_PORT GPIOA
#define	HW_UART2_GPIO_EN RCC_APB2ENR_IOPAEN

// #define HW_CONSOLE_ON_UART
#define	HW_TTY_UART_GETCHAR() uart2_getchar()
#define	HW_TTY_UART_PUTCHAR(ch) uart2_putchar(ch)
#define	HW_TTY_UART_INIT(baud) uart2_init(baud)

#define HW_T_DIO_BIT   (14)
#define HW_T_DIO_PORT  GPIOB
#define HW_T_DIO_INIT           GPIO_PIN_INIT(HW_T_DIO_PORT, HW_T_DIO_BIT, GPIO_MODE_OUTPUT)
#define HW_T_DIO_ON             GPIO_BIT_SET(HW_T_DIO_PORT, HW_T_DIO_BIT)
#define HW_T_DIO_OFF            GPIO_BIT_CLR(HW_T_DIO_PORT, HW_T_DIO_BIT)

#define HW_T_RST_BIT   (6)
#define HW_T_RST_PORT  GPIOB
#define HW_T_RST_INIT           GPIO_PIN_INIT(HW_T_RST_PORT, HW_T_RST_BIT, GPIO_MODE_OUTPUT)
#define HW_T_RST_ON             GPIO_BIT_SET(HW_T_RST_PORT, HW_T_RST_BIT)
#define HW_T_RST_OFF            GPIO_BIT_CLR(HW_T_RST_PORT, HW_T_RST_BIT)

#define HW_T_CLK_BIT   (13)
#define HW_T_CLK_PORT  GPIOB
#define HW_T_CLK_INIT           GPIO_PIN_INIT(HW_T_CLK_PORT, HW_T_CLK_BIT, GPIO_MODE_OUTPUT)
#define HW_T_CLK_ON             GPIO_BIT_SET(HW_T_CLK_PORT, HW_T_CLK_BIT)
#define HW_T_CLK_OFF            GPIO_BIT_CLR(HW_T_CLK_PORT, HW_T_CLK_BIT)

#define HW_T_SWIM_BIT   (8)
#define HW_T_SWIM_PORT  GPIOB
#define HW_T_SWIM_INIT           GPIO_PIN_INIT(HW_T_SWIM_PORT, HW_T_SWIM_BIT, GPIO_MODE_OUTPUT)
#define HW_T_SWIM_ON             GPIO_BIT_SET(HW_T_SWIM_PORT, HW_T_SWIM_BIT)
#define HW_T_SWIM_OFF            GPIO_BIT_CLR(HW_T_SWIM_PORT, HW_T_SWIM_BIT)

// SW SPI support
#define HW_SPI_SW_CS_INIT HW_T_RST_INIT
#define HW_SPI_SW_CS_UP   HW_T_RST_ON
#define HW_SPI_SW_CS_DOWN HW_T_RST_OFF

#define HW_SPI_SW_SCK_INIT HW_T_CLK_INIT
#define HW_SPI_SW_SCK_UP   HW_T_CLK_ON
#define HW_SPI_SW_SCK_DOWN HW_T_CLK_OFF

#define HW_SPI_SW_MISO_INIT GPIO_PIN_INIT(HW_T_DIO_PORT, HW_T_DIO_BIT, GPIO_MODE_INPUT)
#define HW_SPI_SW_MISO_IN   GPIO_IN(HW_T_DIO_PORT, HW_T_DIO_BIT)

#define HW_SPI_SW_MOSI_INIT HW_T_SWIM_INIT
#define HW_SPI_SW_MOSI_UP   HW_T_SWIM_ON
#define HW_SPI_SW_MOSI_DOWN HW_T_SWIM_OFF

#define HW_SPI_OE_ENABLE
#define HW_SPI_OE_DISABLE

#define HW_USB_DP_BIT   (12)
#define HW_USB_DP_PORT  GPIOA

#endif // PCB_H

