#ifndef PCB_H
#define PCB_H

#define HW_TS13

#define	HW_HSE_ENABLED 1 // HSE crystal 8MHz assembled 

#define HW_LED1_BIT   (9)
#define HW_LED1_PORT  GPIOA
#define HW_LED1_INIT  GPIO_PIN_INIT(HW_LED1_PORT, HW_LED1_BIT, GPIO_MODE_OUTPUT)
#define HW_LED1_ON    GPIO_BIT_SET(HW_LED1_PORT, HW_LED1_BIT)
#define HW_LED1_OFF   GPIO_BIT_CLR(HW_LED1_PORT, HW_LED1_BIT) 


#define HW_LED2_ON
#define HW_LED2_OFF

// uart2 == ui
#define HW_UART2_ON 1
#define	HW_UART2_RX_BIT  3
#define	HW_UART2_RX_PORT GPIOA
#define	HW_UART2_TX_BIT  2
#define	HW_UART2_TX_PORT GPIOA
#define	HW_UART2_GPIO_EN RCC_APB2ENR_IOPAEN

// debug interface on UART, keep it off in normal case
// #define HW_CONSOLE_ON_UART / switched off when commented out
#define	HW_TTY_UART_GETCHAR() uart2_getchar()
#define	HW_TTY_UART_PUTCHAR(ch) uart2_putchar(ch)
#define	HW_TTY_UART_INIT(baud) uart2_init(baud)

// HW SPI support
#define SPI1_ON  1

#define HW_SPI_SW_CS_BIT    (4)
#define HW_SPI_SW_CS_PORT   GPIOA
#define HW_SPI_SW_CS_INIT   GPIO_PIN_INIT(HW_SPI_SW_CS_PORT, HW_SPI_SW_CS_BIT, GPIO_MODE_OUTPUT)
#define HW_SPI_SW_CS_UP     GPIO_BIT_SET(HW_SPI_SW_CS_PORT,HW_SPI_SW_CS_BIT)
#define HW_SPI_SW_CS_DOWN   GPIO_BIT_CLR(HW_SPI_SW_CS_PORT,HW_SPI_SW_CS_BIT)

// output enable (level shifter enable)
#define HW_SPI_OE_BIT       (8)
#define HW_SPI_OE_PORT      GPIOA
#define HW_SPI_OE_INIT      GPIO_PIN_INIT(HW_SPI_OE_PORT,HW_SPI_OE_BIT,GPIO_MODE_OUTPUT)
#define HW_SPI_OE_ENABLE    GPIO_BIT_SET(HW_SPI_OE_PORT,HW_SPI_OE_BIT)
#define HW_SPI_OE_DISABLE   GPIO_BIT_CLR(HW_SPI_OE_PORT,HW_SPI_OE_BIT)

// Target GPO reading
#define HW_GPO_IN HW_GPO0_IN
#define HW_GPO0_IN_BIT      (0)
#define HW_GPO0_IN_PORT     GPIOB
#define HW_GPO0_IN_INIT     GPIO_PIN_INIT(HW_GPO0_IN_PORT,HW_GPO0_IN_BIT,GPIO_MODE_INPUT)
#define HW_GPO0_IN          GPIO_IN(HW_GPO0_IN_PORT,HW_GPO0_IN_BIT)

#define HW_GPO1_IN_BIT      (1)
#define HW_GPO1_IN_PORT     GPIOB
#define HW_GPO1_IN_INIT     GPIO_PIN_INIT(HW_GPO1_IN_PORT,HW_GPO1_IN_BIT,GPIO_MODE_INPUT)
#define HW_GPO1_IN          GPIO_IN(HW_GPO1_IN_PORT,HW_GPO1_IN_BIT)

#define HW_GPO2_IN_BIT      (2)
#define HW_GPO2_IN_PORT     GPIOB
#define HW_GPO2_IN_INIT     GPIO_PIN_INIT(HW_GPO2_IN_PORT,HW_GPO2_IN_BIT,GPIO_MODE_INPUT)
#define HW_GPO2_IN          GPIO_IN(HW_GPO2_IN_PORT,HW_GPO2_IN_BIT)

#define HW_GPO3_IN_BIT      (3)
#define HW_GPO3_IN_PORT     GPIOB
#define HW_GPO3_IN_INIT     GPIO_PIN_INIT(HW_GPO3_IN_PORT,HW_GPO3_IN_BIT,GPIO_MODE_INPUT)
#define HW_GPO3_IN          GPIO_IN(HW_GPO3_IN_PORT,HW_GPO3_IN_BIT)

#define HW_GPO4_IN_BIT      (4)
#define HW_GPO4_IN_PORT     GPIOB
#define HW_GPO4_IN_INIT     GPIO_PIN_INIT(HW_GPO4_IN_PORT,HW_GPO4_IN_BIT,GPIO_MODE_INPUT)
#define HW_GPO4_IN          GPIO_IN(HW_GPO4_IN_PORT,HW_GPO4_IN_BIT)

// Target MODE reading
// TEST_MODE
#define HW_MODE0_IN_BIT      (8)
#define HW_MODE0_IN_PORT     GPIOB
#define HW_MODE0_IN_INIT     {GPIO_PIN_INIT(HW_MODE0_IN_PORT,HW_MODE0_IN_BIT,GPIO_MODE_INPUT); GPIO_PUPDN(HW_MODE0_IN_PORT,HW_MODE0_IN_BIT, GPIO_PUPDN_DN);}
#define HW_MODE0_IN          GPIO_IN(HW_MODE0_IN_PORT,HW_MODE0_IN_BIT)

// SCAN_MODE
#define HW_MODE1_IN_BIT      (9)
#define HW_MODE1_IN_PORT     GPIOB
#define HW_MODE1_IN_INIT     GPIO_PIN_INIT(HW_MODE1_IN_PORT,HW_MODE1_IN_BIT,GPIO_MODE_INPUT)
#define HW_MODE1_IN          GPIO_IN(HW_MODE1_IN_PORT,HW_MODE1_IN_BIT)

// FTEST_MODE
#define HW_MODE2_IN_BIT      (10)
#define HW_MODE2_IN_PORT     GPIOB
#define HW_MODE2_IN_INIT     GPIO_PIN_INIT(HW_MODE2_IN_PORT,HW_MODE2_IN_BIT,GPIO_MODE_INPUT)
#define HW_MODE2_IN          GPIO_IN(HW_MODE2_IN_PORT,HW_MODE2_IN_BIT)

// SEL_EXT_CLK
#define HW_MODE3_IN_BIT      (11)
#define HW_MODE3_IN_PORT     GPIOB
#define HW_MODE3_IN_INIT     GPIO_PIN_INIT(HW_MODE3_IN_PORT,HW_MODE3_IN_BIT,GPIO_MODE_INPUT)
#define HW_MODE3_IN          GPIO_IN(HW_MODE3_IN_PORT,HW_MODE3_IN_BIT)

// VCC power switch
#define HW_VCC_RESET_BIT     (0)
#define HW_VCC_RESET_PORT    GPIOA
#define HW_VCC_RESET_INIT    GPIO_PIN_INIT(HW_VCC_RESET_PORT, HW_VCC_RESET_BIT, GPIO_MODE_OUTPUT)
#define HW_VCC_RESET_CLR     {GPIO_BIT_SET(HW_VCC_RESET_PORT, HW_VCC_RESET_BIT); GPIO_MODE(HW_VCC_RESET_PORT, HW_VCC_RESET_BIT, GPIO_MODE_OUTPUT);}
#define HW_VCC_RESET_SET     GPIO_MODE(HW_VCC_RESET_PORT, HW_VCC_RESET_BIT, GPIO_MODE_FLOATING)


#define HW_USB_DP_BIT   (12)
#define HW_USB_DP_PORT  GPIOA

#endif // PCB_H

